### ISSUE TITLE
Incorrect encoding of object handle in `storage_objects_delete`

### ISSUE THREAD

**Issue by youroff** [googleapis/elixir-google-api#6510]
It seems to be impossible to delete objects in folders. GCS expects slashes to be encoded, but the following code passes them unchanged, assuming them the valid parts of URI:
https://github.com/googleapis/elixir-google-api/blob/master/clients/storage/lib/google_api/storage/v1/api/objects.ex#L258
```
iex(3)> URI.encode("dir/file", &(URI.char_unreserved?(&1) || &1 == ?/)) 
"dir/file"
iex(4)> URI.encode("dir%2Ffile", &(URI.char_unreserved?(&1) || &1 == ?/))
"dir%252Ffile"
```

**Comment by dacaga** [comment]
The same goes for storage_objects_get. It's not escaping forward slashes in the object name anymore. Google Cloud Storage's API replies 404s on any object get.

**Comment by stevencorona** [comment]
Seems like all of the storage calls are busted if they have slashes in the file path. This is a pretty major show stopping issue for me.

**Comment by dazuma** [comment]
Fixed in #7159. Will regenerate and rerelease in the next couple days.

**Comment by davidye** [comment]
Looks like this is still broken for storage_objects_copy and storage_objects_rewrite

URI.encode(destination_object, &(URI.char_unreserved?(&1) || &1 == ?/))
